### ISSUE TITLE
Halo 3 Stats Retrieval bug

### ISSUE THREAD

**Issue by Rossimac** [ScottBurger/halo_preserver#2]
Hi there,

When trying to download my Halo 3 stats (Halo 2 and Reach successfully retrieved!) I get the following:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ross\Desktop\bungie\halo_preserver_prod.py", line 286, in halo3_get_files
    halo3_game_ids_list = halo3_game_ids(gamertag)
  File "C:\Users\Ross\Desktop\bungie\halo_preserver_prod.py", line 102, in halo3_game_ids
    custom_pages = int(custom_result.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
PS C:\Users\Ross\Desktop\bungie> python -c "import halo_preserver_prod; halo_preserver_prod.halo3_get_files('Rossimac')"

My GamerTag is Rossimac. If you need any more info, let me know. Only a day left :) Thanks for the tool!

**Comment by Rossimac** [comment]
Ahh, I think the servers are already offline.

Cheers for the tool!

**Comment by ScottBurger** [comment]
End of an era :-(

**Comment by Rossimac** [comment]
Indeed, but I have hope that Insignia (Xbox Live 1.0 replacement service) will get Halo 2 back online at least!
